### ISSUE TITLE
Require clarification for External-MQTT Node Certificate/Keys in Rule Chain

### ISSUE THREAD

**Issue by ankushdineshrana** [thingsboard/thingsboard-edge#101]
**Component**

 * Rule Engine

**Description**
I am trying to send data to an external MQTT broker (AWS Greengrass Moquette) using External-MQTT Node of Thingsboard Rule Engine. Here is what I have done:

1. I have checked via python code, that Greengrass moquette setup works fine using CA Certificates (Root & Device) & Private Key.
2. But when I try to do the same with External-MQTT node, it gives error below:
   
![image](https://github.com/thingsboard/thingsboard-edge/assets/22576029/0a1442b3-f0cb-4091-b4f9-ee093fdaebfa)

3. Here is what my External-MQTT node setup looks like.
![image](https://github.com/thingsboard/thingsboard-edge/assets/22576029/d311dca3-4e7d-4eae-b85b-727b5d44ec4e)

4. I feel like it might be because of mis-match in cert/keys expected formats. The documentation also doesn't specify much about the exact formats for certs/keys i.e. RSA, ECC etc.
![image](https://github.com/thingsboard/thingsboard-edge/assets/22576029/00976f74-1f00-42d2-8a8b-587a5bff336a)

Can someone please suggest if anything being missed here or exact formats that I need to upload.

**Environment**

* OS: Ubuntu on EC2 Instance
* ThingsBoard Server: 3.6.3
* Thingsboard Edge: 3.6.3
* Browser: Chrome Version 123.0.6312.60 (Official Build) (64-bit)

**Comment by ankushdineshrana** [comment]
@JavierNR @volodymyr-babak @peterchen5 @ashvayka Can you please guide me here.

**Comment by volodymyr-babak** [comment]
@ankushdineshrana 

I'm going to answer this question inside next issue on thingsboard project:
https://github.com/thingsboard/thingsboard/issues/10465
