### ISSUE TITLE
Propagate Alarm from Edge to Central Platform

### ISSUE THREAD

**Issue by Borch97** [thingsboard/thingsboard-edge#108]
**Description**
I have multiple instances of edge deployed with multiple devices connected to it. I have Inactivity alarms for this devices and i want to propagate this alarms to be able to see them in the central platform that edge nodes are attatch to.

How can i do this?

Thanks in advance,

___________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by AndriiLandiak** [comment]
Hello, @Borch97

To ensure alarms are propagated for creation or updates, you should configure your specific Edge Rule Chain to transmit alarms to the cloud. For users of Thingsboard Cloud, this configuration can be accessed at: https://thingsboard.cloud/edgeManagement/ruleChains.

![image](https://github.com/thingsboard/thingsboard-edge/assets/50847617/2db81495-3a1c-4e60-8527-287bf549bca0)

**Comment by Borch97** [comment]
Got it. Now it's working.

Thanks.
