### ISSUE TITLE
No able to install TB-Edge CE 3.7.0, 3.6.4 or 3.6.3 => Database initialization scripts fail

### ISSUE THREAD

**Issue by ashdam** [thingsboard/thingsboard-edge#112]
**Describe the bug**
When thingsboard edge is initialization the database creation in postgres it fails in these version we tried with the following error. Note that different error points depending on the version installed.
This corresponds to 3.6.3 

Note that we had no problems installing TB CE in the same machine and using container as well.

![image](https://github.com/thingsboard/thingsboard-edge/assets/169756398/ed84c82d-d7a3-47fe-bb44-b030ff68cc3d)

![image](https://github.com/thingsboard/thingsboard-edge/assets/169756398/a223b32b-056b-449c-b3bc-efc2ad60f677)

Using podman-compose up -d

**using this yml (changed port to avoid conflicts with TB CE )**

`version: '3.8'
services:
  mytbedge:
    restart: always
    image: "thingsboard/tb-edge:3.6.3EDGE"
    ports:
      - "9090:9090"
      - "1884:1884"
      - "6683-6688:6683-6688/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tb-edge
      CLOUD_ROUTING_KEY: 11750622-5672-287b-08f7-11f783c4fdf5
      CLOUD_ROUTING_SECRET: 9rcmmj0paaryh8hwjirj
      CLOUD_RPC_HOST: 127.0.0.1
      CLOUD_RPC_PORT: 7070
      CLOUD_RPC_SSL_ENABLED: false
    volumes:
      - tb-edge-data:/home/admin/tb-community-edge/data
      - tb-edge-logs:/var/log/tb-edge

  postgres:
    restart: always
    image: "postgres:15"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: tb-edge
      POSTGRES_PASSWORD: postgres
    volumes:
      - tb-edge-postgres-data:/var/lib/postgresql/data

volumes:
  tb-edge-data:
    name: tb-edge-data
  tb-edge-logs:
    name: tb-edge-logs
  tb-edge-postgres-data:
    name: tb-edge-postgres-data
`

**Your Server Environment**

* [Live Demo](https://demo.thingsboard.io)
* [ThingsBoard Cloud](https://thingsboard.cloud)
* own setup
  * Deployment: monolith 
  * Deployment type: docker-compose (podman-compose)
  * ThingsBoard Version: TB-Edge CE 3.7.0, 3.6.4 or 3.6.3
  * Community or Professional Edition: Community 
  * OS Name and Version: Ubuntu 

![image](https://github.com/thingsboard/thingsboard-edge/assets/169756398/8be0be41-c925-4dd6-9ea1-9240c95a457d)

**Your Client Environment**

Couln't get to use any client. Error was during installation

**Your Device**

Same as above

* Connectivity
  * MQTT
  * HTTP
  * CoAP
  * Gateway
  * Integration: (Specify name) 
* Device vendor and model

**To Reproduce**
1. execute: podman-compose up -d
2. check the logs: podman-compose logs -f
3. Visualize the error

**Expected behavior**
Software is installed

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**Additional context**
Please feel free to add any other context about the problem here.

________________________________________________________________
**Disclaimer** 

We appreciate your contribution whether it is a bug report, feature request, or pull request with improvement (hopefully). Please comply with the [Community ethics policy](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies), and do not expect us to answer your requests immediately. Also, do not treat *GitHub issues* as a support channel.

**Comment by volodymyr-babak** [comment]
@ashdam 

I did test with the same configuration that you attached and it works like expected:
![2024-06-26_11-54](https://github.com/thingsboard/thingsboard-edge/assets/3466101/4a379430-4fdc-41d0-9b4f-61deeb7d160b)

![2024-06-26_11-54_1](https://github.com/thingsboard/thingsboard-edge/assets/3466101/c9f287b1-bfc4-46c3-b305-c221ba84b535)

But I see the difference in our outputs and looks like in your case docker volumes are not empty and contains some data.
Could you please clarify what is inside docker volumes?
Does it work fine for you if you remove docker volumes before starting containers?
`docker volume rm tb-edge-data tb-edge-logs tb-edge-postgres-data`

**Comment by ashdam** [comment]
Testing done and it worked
