### ISSUE TITLE
My dashboards wont load correctly.

### ISSUE THREAD

**Issue by CalmNite** [thingsboard/thingsboard-edge#122]
Good afternoon, 

I have two thingsboard, one is the main one which has a version 3.6.4 and my edge is version 3.5.1.

I have assigned a dashboard to the edge but when i try to view it i get sone errors. You can see them in the following image. 

![imagen](https://github.com/user-attachments/assets/622c16d4-e29e-4b06-94d2-fae401444539)

When i look in the documentation it says it should work

![imagen](https://github.com/user-attachments/assets/fefe6f3b-f05e-41f5-9dff-163a7b3a7a64)

If i update the version would it work, is it mandatory?

Thanks for the help!

**Comment by AndriiLandiak** [comment]
Hello, @CalmNite! 

It's better to upgrade to 3.6.4 to solve this problem. We are developing the product to ensure backward compatibility with older Edges, which remains our focus. However, occasionally, incompatible features may arise. In this instance, the TB team underwent a refactoring, impacting the compatibility of versions 3.6.4 TB and 3.5.1 Edge, which are almost one year apart in release. 

Also, some new features could be useful for you - for instance, the creation of assets or profiles. You could take a look at the [release notes](https://thingsboard.io/docs/edge/releases/#v351) for more details.

![image](https://github.com/user-attachments/assets/e3bcaf9f-720f-47a4-8afe-8591486b069d)

**Comment by CalmNite** [comment]
@AndriiLandiak 

Okey I will update. Thanks for the help!! 😀

**Comment by AndriiLandiak** [comment]
Please feel free to reopen it if you have any more questions or if the problem exists after the upgrade.
