### ISSUE TITLE
Can I send a persistent RPC via the TB Edge HTTP API?

### ISSUE THREAD

**Issue by dratasich** [thingsboard/thingsboard-edge#123]
**Component**

 * HTTP API
 * Rule Engine

**Description**
Can I send persistent RPCs to the Edge?
```
###
POST {{host}}/api/rpc/oneway/{{rpb_device_id}} HTTP/1.1
Content-Type: application/json
X-Authorization: Bearer {{auth_token}}

{
  "method": "MyMethod",
  "params": {
    "test": "twoway persistent RPC",
    "file": "test.http"
  },
  "additionalInfo": {
    "extra": "test"
  },
  "retries": 3,
  "persistent": true
}
```
Where `{{host}}` is either the TB URL or the edge URL:
* TB URL: This returns 200 with a ThingsBoard instance running `v.3.6.4PE`
  ![image](https://github.com/user-attachments/assets/211e639a-5688-4994-ba93-04df30ac0272)
* Edge URL: but a timeout 504 for the edge instance running `v.3.6.4EDGEPE`.
  ![image](https://github.com/user-attachments/assets/ab7161bf-cab3-437b-9a32-51d4560facc0)

I used the default root rule chains where the `RPC call request` node receives a `RPC_CALL_FROM_SERVER_TO_DEVICE`. The screenshots above are from these nodes (TB vs. edge respectively)

**Environment**
 * OS:  running with your docker images
 * ThingsBoard: v.3.6.4PE
 * ThingsBoard Edge: v.3.6.4EDGEPE

Thanks in advance!
Kind regards,
Denise

**Comment by dratasich** [comment]
OK, sry, on another edge instance it works (I get 200 and rpcId) ... seems like I have broken the Rule Chains somehow. Or it has something to do with the setup.

**Comment by dratasich** [comment]
The problem was that the device was created in the main instance. As soon as I created the device in the edge (as it is meant to be in my use case), the call works as expected.
My learning: the RPCs are meant to be executed in the instance where the device has been created (regardless if it is assigned to the edge(?)).

**Comment by AndriiLandiak** [comment]
Hi, @dratasich! 

Thanks for the request. Unfortunately, there is an issue with persistence RPC. The message is always identified as persistence=false. We could provide a hotfix image for both PE and EDGE-PE, could you send me an email - alandiak@thingsboard.io and I'll provide you details?

**Comment by dratasich** [comment]
Hi @AndriiLandiak,
ah, this issue of persistence=false is when sending an RPC request in the rule chain (?) - I have a workaround for that. For now, there is no hotfix image necessary. Thanks!
