### ISSUE TITLE
[Question] OTA update packages not visible in ThingsBoard Edge

### ISSUE THREAD

**Issue by JeromeJalkh** [thingsboard/thingsboard-edge#13]
**Component**

 * Generic

**Description**
Hello,

I have an instance of ThingsBoard (central) and an instance of ThingsBoard Edge with everything working fine.
The only problem is that when I add an OTA update package to the ThingsBoard (central), it is only visible (and therefore can be assigned) on the ThingsBoard (central).
However, on the Edge it says "No compatible Firmware OTA Update packages provisioned." (in fact no update package is visible on the Edge).

When I checked the postgres databases of both instances, I saw that the ota_package table in the database of the ThingsBoard (central) was filled with the created OTA update packages, however the ota_package table in the Edge's database is empty.

Is it normal that the OTA packages are not synced between the ThingsBoard (central) and ThingsBoard Edge?

**Comment by volodymyr-babak** [comment]
Hello @JeromeJalkh 

OTA is not available yet on the edge. 
Development of this feature just started on Friday and we are targeting to deliver it in the 3.4 release soon.
