### ISSUE TITLE
what should be format of licence.data file and where to store this file

### ISSUE THREAD

**Issue by nepolean2** [thingsboard/thingsboard-edge#3]
Thingsboard.io

 * Installation
 * Generic

**Description**
what should be format of licence.data file(schema) and where to store this file
**Environment**
 * OS:  Linux + docker
 * ThingsBoard: latest

**Comment by volodymyr-babak** [comment]
@nepolean2 
format of the license.data file is proprietary information. You can store this file in any location, that is accessible by the Edge service.
