### ISSUE TITLE
[Question] Install scrip fail when i try to execute install_dev_db.sh

### ISSUE THREAD

**Issue by ertugertshkulaku** [thingsboard/thingsboard-edge#38]
**Component**
 * Installation

**Description**
I am trying to install thingsboard-edge building from sources but when I try to execute install_dev_db.sh  this error occurs.
mvn clean install -DskipTests  build sucess.
![Screenshot_399](https://user-images.githubusercontent.com/60472698/216566451-c02dbb3a-a0ee-42d6-8a99-5fbb3ffe5b49.png)

**Environment**
 * OS:  Garuda Linux / ubuntu 20

**Comment by ertugertshkulaku** [comment]
I have created a PR where i FIXED this bug.

**Comment by volodymyr-babak** [comment]
pull request merged - closing this issue.
