### ISSUE TITLE
Thingsboard Edge PE displays duplicates of the same device created by the IoT Gateway

### ISSUE THREAD

**Issue by apadEnlace** [thingsboard/thingsboard-edge#4]
Hi!

**Thingsboard Edge PE**

Note: I'll refer to Thingsboard as "TB" in the rest of the message

**Description**
I have a TB IoT Gateway collecting data from CAN devices. I'm testing sending this data to a TB Edge PE instance running in a different computer in same network. When a CAN device generates a value, TB Edge, correctly, shows the device with the corresponding telemetry value. However, when the device doesn't get a new telemetry value before the device disconnects ("lastDisconnectTime" attribute updates), TB Edge creates a new device showing the newly received telemetry value; and it does this every time the device disconnects:

![image](https://user-images.githubusercontent.com/99991163/162071987-a199e8f0-9d8c-4202-bec8-9c6c2091fd2d.png)

**Where is that string at the end of the Device Name coming from? How can I set up TB Edge to not add that string, so it doesn't creates new devices?** 

I suspect TB Edge is the one adding this string to the name, as previously I had tested the TB IoT gateway connected directly to an instance of TB Server PE, and the name do not show that string that TB edge is showing. Screenshot of name of device configured in TB Gateway:

![image](https://user-images.githubusercontent.com/99991163/162072087-66b9b9c7-5e71-4275-b46a-6705017d021a.png)

OS: Ubuntu 20.04
ThingsBoard: TB Edge PE (3.3.4pe), TB IoT Gateway (latest - installed a couple of weeks ago) and TB Server PE 3.3.2
Browser: Chrome Version 100.0.4896.60

**Comment by volodymyr-babak** [comment]
@apadEnlace 

this string is added to the device on the Edge in case the device name conflicts with the one, that is already created on the TB cloud. 
Do you have a device with the same name on the TB cloud?
