### ISSUE TITLE
[Question] How to migrate to tb-edge v3.4.3?

### ISSUE THREAD

**Issue by AndreMaz** [thingsboard/thingsboard-edge#42]
**Component**

 * Installation

**Description**
I'm having trouble migrating my TB-edge instance to v3.4.3. The `upgrade-tb-edge.sh` @ 3.4.3 the script fails because it tries to migrate from 3.4.2 which does not exist in Docker registry (Link https://hub.docker.com/r/thingsboard/tb-edge/tags) 

NOT running`upgrade-tb-edge.sh` @ 3.4.3 produces the following error:

>  tb-edge  org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [tb_user_email_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

Note: Migration to v3.4.1 worked fine and everything seems to be working. 

**Environment**

 * ThingsBoard: Docker Image v3.4.4 (Link: https://hub.docker.com/layers/thingsboard/tb-postgres/3.4.4/images/sha256-9338fc2a02595531992878b1f68f8354a6f31d0dd08c51e0212afe1838aef28e?context=explore ) 
 * ThingsBoard Edge:  Docker image v3.4.3 (Link https://hub.docker.com/layers/thingsboard/tb-edge/3.4.3EDGE/images/sha256-20fd55472de22ddc012b8dbee380ccb7ba3c037dde09e01082678c2934a92171?context=explore )

**Comment by volodymyr-babak** [comment]
@AndreMaz 

could you please try to upgrade your Edge component using these instructions?
https://thingsboard.io/docs/user-guide/install/edge/upgrade-instructions/#docker-linux-mac-343

**Comment by volodymyr-babak** [comment]
@AndreMaz 

sorry for inconveniences. There is indeed issue in the upgrade file.
But you can skip this upgrade step.
Please simply update your main docker-compose.yml file and set TB edge version to 3.4.3:
![image](https://user-images.githubusercontent.com/3466101/224049651-9a73886d-3beb-4ede-b5d6-82a0c32495c6.png)

So please skip upgrade step and it should work. 
I'm going to update docs soon and remove this step.

**Comment by AndreMaz** [comment]
Hi @volodymyr-babak 

I've tried that. TB edge starts but then it starts throwing erros like:

> tb-edge org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [tb_user_email_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

I guess that something changed in DB schema between 3.4.1 and 3.4.3

**Comment by AndreMaz** [comment]
I've ended up deleting the containers and volumes of TB edge and Postgres. After a "clean install" TB edge started to work properly.

However, when I pressed "Sync Edge" I got another error at TB edge.

I opened another ticket here: https://github.com/thingsboard/thingsboard-edge/issues/46

**Comment by volodymyr-babak** [comment]
@AndreMaz 

You are correct - upgrade step is required. 
I was wrong in my previous comment. 
I had updated docker images to be able correctly handle upgrade from 3.4.1 to 3.4.3 using docker images.
