### ISSUE TITLE
[Bug] Device profile editing is not possible

### ISSUE THREAD

**Issue by ricktauss** [thingsboard/thingsboard-edge#6]
**Describe the bug**
In the menu "Device profile" it is not possible to create or delete profiles. If a new device is created on edge it is possible to create a new device profile via this menu. Deleting afterwards is not possible.

**Your Server Environment**
* own setup
  * Deployed as Docker on Raspberry Pi 4B
  * thingsboard/tb-cassandra 3.3.4.1 (latest)
  * Ubuntu 20.04 LTS

**Your Client Environment**
**Desktop:**

* Windows 10
* Chrome
* Docker Desktop with thingsboard/tb-edge 3.3.4Edge

**To Reproduce**
1. Login into Thingsboard Edge as Tenant Administrator
2. Click on Device Profiles

**Expected behavior**
Device Profiles can be created and deleted the same way as in Thingsboard  Server

![Edge_DeviceProfile](https://user-images.githubusercontent.com/57318706/166150644-19c6db70-edda-4c4c-85b6-82cfeded85e8.JPG)
![Server_DeviceProfile](https://user-images.githubusercontent.com/57318706/166150646-a95df720-e99b-4b36-9ba1-5ec03c2f28e8.JPG)

**Comment by ricktauss** [comment]
A second problem according to the Device profiles is following:

If a device is created with a custom device profile on the server and is assigned to the edge, the edge immediately fails because the device profile is not existing on the edge instance.

What is the proper handling with this issue?

I would expect the device profile to be downloaded first if not available and then the device. 


Kind regards

**Comment by volodymyr-babak** [comment]
hi @ricktauss 
creation of the device profile is not available at the moment on the edge. Most probably we have a bug, that allows you to create it on the edge from the device creation window. 

Regarding the second topic - that is true - if the device profile is created on the cloud, it should be provisioned automatically to all edges.
In your case you had created a custom device profile together with the creation of the device - and most probably this case is not covered by tests and has a bug. I'm going to double-check it as well and get back to this issue. 
At the moment, as a workaround - please create a custom device profile on the cloud and then the device, using this device profile. 
Thanks for posting these issues!

**Comment by ricktauss** [comment]
Hello @volodymyr-babak ,
ok if it is not available on edge its fine.

I am not sure but i think i have created the device profile on the cloud and afterwards alos the device on the cloud. The device profile was not pushed down to the edge.
But i am not sure and will test this with a new edge instance and give feedback if this is working or not.

Thank you!

**Comment by ricktauss** [comment]
Hello @volodymyr-babak ,

i have tested it that way as you said and it is working fine.

1. Create Device profile on cloud  =>  is synchronized automatically
2. Create Device on cloud
3. Assign Device to edge  =>  is synchronized automatically

Thank you!

**Comment by ricktauss** [comment]
Hello @volodymyr-babak,

the synchronizing from the Device profile from cloud to edge is just working if the transport type of the device is set to default.

If a device profile for e. g. with MQTT is created, this profile is not synchronized to the edge.

![profile_sync](https://user-images.githubusercontent.com/57318706/166463921-543a1d45-cd01-406e-a186-48a058f2506d.jpg)

**Comment by ricktauss** [comment]
Hello @volodymyr-babak ,
when will the next release happen? Generally i having a little bit stress, but if there is a release planned within a week i can wait ;)

Thank you!

**Comment by volodymyr-babak** [comment]
@ricktauss probably a month or two - I can't answer that precisely at the moment. 
If you are using the CE version, I can provide you with deb or other artifacts, that will contain the latest release and the fix for this bug. 
Just let me know what installation type you are using.

**Comment by ricktauss** [comment]
@volodymyr-babak ok thats too long for me now ;)

I am using the CE platfrom version as Docker container on Linux (ARM64). The following container: thingsboard/tb-cassandra. Image should be the latest -> 3.3.4.1

**Comment by volodymyr-babak** [comment]
@ricktauss 

I'm going to upload these images to my personal docker-hub account (**volodymyrbabak**) and set the version to **3.3.4.2**.
Will that work for you?

**Comment by ricktauss** [comment]
@volodymyr-babak 
Yes that's fine.  Thank you!

**Comment by volodymyr-babak** [comment]
@ricktauss 
please take a look at this repository:
https://hub.docker.com/repository/docker/volodymyrbabak/tb-cassandra

You can simply replace `thingsboard/tb-cassandra` with `volodymyrbabak/tb-cassandra` image and restart the docker container.

Let me know if you'll have any additional issues.

**Comment by ricktauss** [comment]
@volodymyr-babak 

Thank you for the image!

I have done following and also had some issues:

1. Stopped containers
2. Changed docker compose file to the new image
3. Pulled and started container
4. -> A lot of exceptions

Next thing i have done:
1. Deleted .tb-data and .tb-logs files and created new ones
2. Started container again
3. Everything ok -> Platform worked

On the edge side:
1. Created new edge volums on windows
2. Stated edge with new credentials from platform
3. As i checked the Downlink info for the edge after some time i got the following error like in the picture

After the exception:

1. Stopped and restarted edge again
2. Tried to provision new device profile
3. -> Everything ok now


![exception](https://user-images.githubusercontent.com/57318706/166523262-50622233-6172-4bdf-999c-cb40389d87b8.JPG)

**Comment by volodymyr-babak** [comment]
@ricktauss 
double-checking - do you have any issue after the full redeploy and restart of CE server and edge instance? Or everything is OK at the moment?

**Comment by ricktauss** [comment]
@volodymyr-babak 
I have worked a little bit with server and edge and everything is looking good at the moment.
