### ISSUE TITLE
[Question] How to reduce the Device data sampling time from edge to cloud?

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard-edge#61]
**Component**

 * Rule Engine
 * Generic

**Description**
Is it possible to reduce the Device traffic at edge based on the sampling time? For example, if a Device is sending the telemetry to Cloud via Edge at the sampling rate of 1 minute, is there any method to reduce the traffic at Edge and send the data to cloud after every 5 minutes? 

I have few Devices which are sending the data at the sampling rate of 1 minute, but the Cloud Rule Engine executions are in high volume. Please see the below attached screenshot for Transport, Rule Engine Executions, and JavaScript API count.

![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/b31d9596-780f-4f19-b15e-87ca2799fb0f)

**Environment**

 * OS:  Ubuntu 22.04
 * ThingsBoard Edge: 3.5.0EDGEPE

**Comment by volodymyr-babak** [comment]
Hello @akseerali,

From your screenshots, it seems you're using the Professional Edition. Achieving your goal with the Community Edition might be a bit complex, but with the Professional Edition, it should be rather straightforward.

For this, you can use the 'Aggregate Stream' rule node on the edge. With this configuration, the timeseries data would only be pushed to the edge based on a preconfigured interval, not every 1 minute, which seems to be your device's timeseries rate:
![16-40-28](https://github.com/thingsboard/thingsboard-edge/assets/3466101/fa60146e-5259-41bd-b431-005bf3d483c5)


Please let me know if you need any further clarification or assistance.

**Comment by akseerali** [comment]
Hi @volodymyr-babak,

Many thanks for the help.
