### ISSUE TITLE
[Question] Not able to login into TB Edge (localhost:8080)

### ISSUE THREAD

**Issue by AIOTEL-sanjanaa** [thingsboard/thingsboard-edge#69]
Not able to login into TB Edge (localhost:8080)

 * Generic

**Description**
So I followed the docker installation in Linux for TB-Edge, and set all the necessary parameters in the yml file. I am receiving the attribute updates in demo.thingsboard.io as shown below.
![image](https://github.com/thingsboard/thingsboard-edge/assets/132904735/56f03994-9e76-48e5-9c62-2312933bce92)
But not able to login into the localhost:8080 with the credentials I've signed in with demo.thingsboard.io. 
![image](https://github.com/thingsboard/thingsboard-edge/assets/132904735/1e70a4f4-01e5-41b9-8059-3ef8c5f0164e)

**Environment**

 * OS:  Ubuntu
 * Browser: Firefox 115.0.2

**Comment by volodymyr-babak** [comment]
@AIOTEL-sanjanaa 

There are two potential scenarios that might be causing this:

- Sync Issue: The edge may not be synchronizing correctly with the server. To help us diagnose this possibility, could you please attach the logs from your edge container to this ticket?

- Authentication Method: Your user account on cloud might not have a password, indicating you're using OAuth2 for authentication. Please verify that your user account on demo.thingsboard.io has a password set and that you're not relying solely on OAuth2 for authorization.

**Comment by AIOTEL-sanjanaa** [comment]
The password was not set. Thank you. Issue got solved.
