### ISSUE TITLE
[Question] Why no Docker build for armv7l

### ISSUE THREAD

**Issue by ferguscan** [thingsboard/thingsboard-edge#7]
**Component**
 * Installation

**Description**
The official Edge Docker images are available for `arm64` and `amd64` architectures only.  Would it be possible to add `armv7l`?  I would like to run TB Edge on a Raspberry Pi 3 with a 32-bit OS.  Please let me know if there's anything I can do to help.  Thanks!

**Environment**
 * OS:  Raspbian Buster (32-bit)

**Comment by volodymyr-babak** [comment]
hi @ferguscan 
thanks for the interest in the product. We'll review this in detail and provide feedback on the possibility of adding this feature. 
Probably we can add this support in the next release if no technical issue that will block this.

**Comment by ferguscan** [comment]
Thanks @volodymyr-babak 

Are there instructions for building the image?  What CI tool do you use to build them?  Would you like me to add GitHub Actions for this purpose?

**Comment by volodymyr-babak** [comment]
@ferguscan 

first, please build edge project from sources:
https://thingsboard.io/docs/user-guide/install/edge/building-from-source/

Update **docker.repo** property in the msa project of pom.xml file to your docker hub id or docker repository name:
![image](https://user-images.githubusercontent.com/3466101/169891222-82c30c9b-284a-4672-8b7d-74d7745cb6e7.png)

Once this is done you can execute next command:
`mvn clean install -DskipTests -Ddockerfile.skip=false -P push-docker-amd-arm-images`

linux/amd64 and linux/arm64 should be pushed into your docker repository.

**Comment by volodymyr-babak** [comment]
**arm/v7** architecture for Edge CE and Edge PE docker images was added for 3.4.3 release images and is going to be available in next releases.
