### ISSUE TITLE
[Question] Thingsboard Edge deployment scenario

### ISSUE THREAD

**Issue by shashank-r25** [thingsboard/thingsboard-edge#70]
Hello,

What are the deployment scenarios for Thingsboard Edge?
How many devices and requests can be handled by a single Edge?
If we want to enhance the Thingsboard Edge, what measures need to be taken or considered?

Thank You,

**Comment by volodymyr-babak** [comment]
@shashank-r25 

> What are the deployment scenarios for Thingsboard Edge?

ThingsBoard Edge is a lightweight edge computing platform that acts as a bridge between devices at the network edge and the ThingsBoard Cloud or on-premises installations. It allows you to collect, process, and send data from IoT devices to the central ThingsBoard server while providing local device management and rule engine capabilities.

Here are some common deployment scenarios for ThingsBoard Edge:

- Limited Connectivity: In remote areas where connectivity is intermittent, ThingsBoard Edge can collect and store data locally, and then sync with the main ThingsBoard server when the connection is available.

- Data Volume: In scenarios where devices produce a massive volume of data, ThingsBoard Edge can aggregate and preprocess the data at the edge, sending only necessary or processed data to the main server, thereby saving bandwidth and storage.

- Low Latency Operations: For operations that require real-time responses, ThingsBoard Edge can process data and act on it instantly without waiting for round trips to a central server. This is crucial in industries such as manufacturing or real-time monitoring.

- Regulatory Compliance: In some regions, there might be regulations that prevent certain data from being sent outside a specific geographical boundary. ThingsBoard Edge can process and store the data locally, ensuring that sensitive or regulated data doesn't leave the premises.

- Resilience and Redundancy: Edge deployments can continue to operate even if the central server is down or unreachable. This ensures that mission-critical applications have minimal downtime.

- Security: By processing data at the edge, sensitive information can be kept within a local network, reducing exposure to potential external threats.

- Firmware Updates: ThingsBoard Edge can facilitate firmware updates for IoT devices. In environments with numerous devices, managing updates can be challenging. Edge deployment can help streamline this process.

- Integration with Local Systems: In some scenarios, IoT data might need to be integrated with local databases or systems. ThingsBoard Edge can serve as an integration point, communicating with both IoT devices and local systems.

- Cost Savings: By preprocessing and filtering data at the edge, businesses can reduce the amount of data sent to the cloud, leading to potential cost savings in terms of data storage and transfer.

- Distributed Architecture: For organizations that have multiple locations or branches, deploying ThingsBoard Edge in each location ensures local processing and management while maintaining a connection with the central server for consolidated data views and management.

In conclusion, ThingsBoard Edge offers the flexibility to address various challenges faced in IoT deployments, from connectivity and latency concerns to security and regulatory compliance. The choice of deploying ThingsBoard Edge depends on the specific needs and constraints of the IoT project in question.

> How many devices and requests can be handled by a single Edge?

The capacity of a single edge to handle devices and requests is largely influenced by the hardware it's deployed on.

We recently conducted a performance test where we set up 1,000 devices on a single edge and pushed messages at a rate of 2,000 per second (which translates to 2 messages every second for each device). This test ran continuously for 3 hours without any issues. You can see the details here: [Test Results](https://github.com/thingsboard/thingsboard-edge/issues/47#issuecomment-1506840390).

Given more robust hardware resources, I believe the edge could potentially handle even greater numbers of devices or messages.

> If we want to enhance the Thingsboard Edge, what measures need to be taken or considered?

You can build the edge from sources and implement any improvements you desire.
Here's the link to set up the edge from sources: https://thingsboard.io/docs/user-guide/install/edge/building-from-source/

**Comment by shashank-r25** [comment]
@volodymyr-babak 

Thank you for your quick reply.

What will the licensing for Thingsboard Edge CE ?
reference Link/ documentation regarding the licensing.

**Comment by volodymyr-babak** [comment]
@shashank-r25 

The Edge CE version is covered under the Apache License, Version 2.0. You can find the details of this license in the Edge repository here: [Apache License in Edge Repository](https://github.com/thingsboard/thingsboard-edge/blob/master/LICENSE).

**Comment by shashank-r25** [comment]
@volodymyr-babak 

Thank you for clarifying the questions I had.
