### ISSUE TITLE
[Question] Edge PE 3.5.1.1 can't push cloud events after encountering exception error

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard-edge#71]
**Component**

Rule Engine

**Description**
I am using Transformation-Script Node at the edge and cloud rule chains. The issue is, there are exception issues at the edge and cloud resulting from a JavaScript code. Under the "Rule Engine Statistics" in "API Usage", the cloud is now showing "Script invocation is blocked due to maximum error count 3" error. 

![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/50e565ec-5e9d-4ee2-bfab-e8b401bb23b1)

After this error, I have updated the edge and cloud rule chains and the "Downlinks" section under the edge instance is also showing "deployed" status; however, the rule chain at the edge is still same. Moreover, the edge is not pushing the telemetry data to the cloud. The status of cloud events at the edge is pending. 

![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/9c299dce-3411-4b57-9fb8-ed77f6f48770)

I have further tried to resolve this issue by restarting the edge container, but this has not worked so far.

**Question/Discussion**

- How to resolve the script invocation issue?
- Is there a way to synchronize the edge with cloud to update the pending changes in rule chain from cloud?
- The edge status is showing "Connected", but the telemetry data is pending in the cloud events.
- The rule chain at the edge is unable to update, hence it is still showing the errors from rule chain, but there is no "Script invocation is blocked due to maximum error count 3" error at the edge.
- I think one method would be to use a previous working backup of edge to clear all the issues, but this can cause the loss in data.

**Environment**

 * OS:  UBUNTU 22.04
 * ThingsBoard Edge: 3.5.1.1 PE

**Comment by volodymyr-babak** [comment]
@akseerali,

Could you please attach the logs from your edge container to help us troubleshoot the issue? I'll be in a better position to answer your questions after reviewing the logs. I suspect there are two possible issues:

- There may be too many messages on the edge, and the default configuration is unable to process them in time.
- The edge might not be synced with the cloud due to some error.

**Comment by akseerali** [comment]
Hi @volodymyr-babak 

This issue appeared after the rule chain in the cloud threw a few exception errors during the execution of a JavaScript function on data originating from Edge. That is why it could not sync even after restarting the Edge container.

We used the most recent backup to clear this issue, and that is why we could not get old logs. The issue only appeared after fixing the rule chain.

Some observations: If a few exception errors result from data processing/transforming in the edge rule chain using JavaScript, it will throw exception errors in the API statistics. However, the Edge will continue to work. If the same error appears in the cloud, then there is a limit to exception errors, and the cloud will no longer synchronize with the edge instance to make any changes in devices, assets, dashboards, or rule chains.

Further testing can be done on this scenario to replicate and fix the issue in future.

**Comment by bcblr1993** [comment]
@akseerali I’m using the same version 3.5.1.1 CE EDGE and encountered the same issue as you, but I don’t have the rule engine node you mentioned. How can I resolve this?
