### ISSUE TITLE
[Question] Edge widgets error

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard-edge#81]
**Component**

 * UI
 * Rule Engine
 * Generic

**Description**
The widgets are not working after throwing the below error. Is there a way to clear this error from the edge database? Here are some of the observations:

- The edge and cloud are synchronized and able to communicate.
- Any changes made from the cloud are updated to the edge.
- The issue seems to be related to widgets.
- The edge is producing the same errors even though all the Devices, Assets, Rule Chains, and Dashboards are unassigned. The root rule chain is also disabled from the input node.
- Tried to upgrade the edge pe version from 3.5.1.1PE to 3.6.0PE, but was unsuccessful.
- The same setup has been running for 1-2 months. I am not sure why, but it recently caused an issue after upgrading the cloud version to 3.6.0.
- Could it be related to this issue? [Link](https://github.com/thingsboard/thingsboard-edge/issues/5)
- Please check the edge and postgres logs below.
[tb-postgres-logs.txt](https://github.com/thingsboard/thingsboard-edge/files/12961521/tb-postgres-logs.txt)
[tb-edge-logs.txt](https://github.com/thingsboard/thingsboard-edge/files/12961524/tb-edge-logs.txt)

`tb-edge  | org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement`
.
.
.
`tb-edge  | 2023-10-17 22:02:47,645 [grpc-default-executor-0] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 0, SQLState: 22001
tb-edge  | 2023-10-17 22:02:47,645 [grpc-default-executor-0] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - ERROR: value too long for type character varying(255)
tb-edge  | 2023-10-17 22:02:47,646 [grpc-default-executor-0] INFO  o.h.e.j.b.internal.AbstractBatchImpl - HHH000010: On release of batch it still contained JDBC statements
tb-edge  | 2023-10-17 22:02:47,647 [grpc-default-executor-0] ERROR o.t.s.s.c.DefaultDownlinkMessageService - Can't process downlink message [downlinkMsgId: 1732855390`
 

**Here is the widgets screenshot**
![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/7abc8869-502c-45c2-a52b-45a199acc412)

**Environment**

 * OS:  Ubuntu 22.04.3 LTS
 * ThingsBoard Edge PE: 3.5.1.1 PE

**Comment by volodymyr-babak** [comment]
@akseerali,

Thank you for raising this issue. 

Indeed, some widgets on the edge break when an older version of the edge is connected to the cloud version 3.6. This is because the edge syncs with the cloud to get the most recent widget configurations. With the 3.6 release, widgets underwent significant changes, making older versions of the edge incompatible with the new cloud widgets.

Can you please upgrade your edge to the latest 3.6 version? 
I noticed you mentioned encountering errors during the update - could you share details about those errors?

**Comment by akseerali** [comment]
Hi @volodymyr-babak 

We have again tried to update the ThingsBoard edge version, but it showed the same error.
Please find attached the logs obtained while upgrading the ThingsBoard Edge PE from version 3.5.1.1 to version 3.6.0.
Please share any information on how to cope with this issue. Thanks

[upgradation logs for 3.6.0 - v1.0.txt](https://github.com/thingsboard/thingsboard-edge/files/13048400/upgradation.logs.for.3.6.0.-.v1.0.txt)

**Comment by volodymyr-babak** [comment]
@akseerali,

Kindly refer to this upgrade guide:
https://thingsboard.io/docs/user-guide/install/pe/edge/upgrade-instructions/#ubuntucentos-36

I suspect you might be using the wrong command. Please ensure you use the following:
`sudo /usr/share/tb-edge/bin/install/upgrade.sh --fromVersion=3.5.1`

**Comment by akseerali** [comment]
Hi @volodymyr-babak 

Thank you for the hint.

Somehow the edge was not upgraded from v3.5.1.1 to v3.6.0, but it updated the version number in the ".upgradeversion" file.
The upgrading issue has been resolved by first manually changing the version from 3.6.0 to 3.5.1 from docker container, and then upgrading the edge to v3.6.0 by following this [link](https://thingsboard.io/docs/user-guide/install/pe/edge/upgrade-instructions/#docker-linux-mac-36).

The issue with the widgets has also been successfully resolved. Thanks
