### ISSUE TITLE
arm64 problem

### ISSUE THREAD

**Issue by Kevin-ox** [thingsboard/thingsboard-edge#84]
Hello! I installed the edge on arm64, the installation and operation were normal, but I could not log in, there was no data in the database, and the data in the cloud was not synchronized.
[tb-edge.log](https://github.com/thingsboard/thingsboard-edge/files/13263258/tb-edge.log)
[install.log](https://github.com/thingsboard/thingsboard-edge/files/13263260/install.log)

**Comment by Kevin-ox** [comment]
I manually clicked the sync edge on the cloud and it seemed to sync, but there were a lot of errors!
[tb-edge.log](https://github.com/thingsboard/thingsboard-edge/files/13263316/tb-edge.log)

**Comment by volodymyr-babak** [comment]
@Kevin-ox 

Hello, for some reason widget bundle can't be processed by edge.
Are you connecting to some public cloud or it's private?
Can you connect to this cloud from your PC using some other edge? Do you have any issues?
If you have, is it possible to create demo tenant account for me to test connection from my side?
I suppose 3 possible reasons:
1. connections issues 
2. bundle contains something that could not be processed by edge
3. bug in the edge conversion layer

**Comment by Kevin-ox** [comment]
I am using a private cloud with no external access, maybe my cloud is a 3.5.1 upgrade

**Comment by volodymyr-babak** [comment]
@Kevin-ox 
thanks for the provided details.
I suppose in your case you are using newer version of Edge with older version of the server.
Please read carefully warning message in the installation guide:
https://thingsboard.io/docs/user-guide/install/edge/deb-installation/
![2023-11-14_18-26](https://github.com/thingsboard/thingsboard-edge/assets/3466101/326be523-5169-4002-8b6e-ca8a2a6cbaf2)

You can't use newer version of edge with older version of the cloud, only vise versa.
Please upgrade your cloud to 3.6.0 version and your problem should be solved.

**Comment by Kevin-ox** [comment]
This issue was resolved and a new issue was found, I cloud using 3.6.1, edge using 3.5.1, nodes would be incompatible such as "save attributes"
