### ISSUE TITLE
[Bug] MQTT subscription does not work as expected

### ISSUE THREAD

**Issue by ricktauss** [thingsboard/thingsboard-edge#9]
**The bug**
If a device profile for MQTT is created with any customized topic, it is possible to send data to the topic but subscribing fails.

**Server Environment**
Docker Setup on Ubuntu Server on RaspberryPi
Docker image:  volodymyrbabak/tb-cassandra 3.3.4.2

**Edge Environment**
Docker Setup on Ubuntu Server on RaspberryPi
Docker image: thingsboard/tb-edge 3.3.4EDGE

**To Reproduce failed subscription**
  1. Create device profile
  2. Create user defined topics for telemetry and attributes
  3. Try to subscribe to this topics
Screenshot documentation:
Device profile:
![1](https://user-images.githubusercontent.com/57318706/169062208-911d7251-ca42-422c-81d4-e1f32282e7d1.JPG)
MQTTX client try to subscribe:
![2](https://user-images.githubusercontent.com/57318706/169062348-167892c6-a703-4cdc-b613-639324369d43.JPG)
Log message from docker container:
![3](https://user-images.githubusercontent.com/57318706/169062408-29d7d451-e395-4f23-ad71-ef30e017bfca.JPG)

**Comment by volodymyr-babak** [comment]
@ricktauss 
hello, could you please specify details on the MQTT client host - are you connecting to TB edge or to TB server?

**Comment by ricktauss** [comment]
@volodymyr-babak 
Hello,
as MQTT Client Software i use MQTTX on Windows PC for testing publishing and subscribing.

I have created a device once for the ThingBoard Plattform and once for the ThingsBaord Edge. For both variants it is possible to publish to the telemetry and the attribute topic which was defined in the device profile. But subscribing doesn't work on any plattform or topic.

**Comment by volodymyr-babak** [comment]
@ricktauss 

I believe this is covered in the answer https://github.com/thingsboard/thingsboard-edge/issues/10#issuecomment-1135039863
Please let me know if you are interested in any additional details.

**Comment by ricktauss** [comment]
@volodymyr-babak 
Yes this covers both. I will also close this issue as completed
