### ISSUE TITLE
[Bug] Problem loading widget configuration. Probably associated widget type was removed

### ISSUE THREAD

**Issue by donskytech** [thingsboard/thingsboard-edge#92]
**Describe the bug**
I followed everything in this [Thingsboard Cloud Getting Started](https://thingsboard.io/docs/paas/getting-started-guides/helloworld/#step-7-share-dashboard-with-customers).
I can see the data coming in.  However, when I shared the dashboard with one of the customers.  I am getting the below error when he views the dashboard.
![image](https://github.com/thingsboard/thingsboard-edge/assets/69466026/ddc41d4b-e365-46ba-852f-17c8b3a6e240)

I do not have this issue when I am the one viewing the dashboard.  What could be the error?
**Your Server Environment**

* cloud.thingsboard.io

**Your Client Environment**

Thingsboard Cloud

* Connectivity
  * MQTT

* Device vendor and model

**To Reproduce**

**Expected behavior**
I should be able to see the dashboard.

**Screenshots**
Please see above.

**Additional context**

**Comment by volodymyr-babak** [comment]
@donskytech 

Hello, 
it's not clear from the description, how this bug is related to the Edge service?
Do you have issues on the Edge service, or only on the thingsboard.cloud? 
Please provide more details on your Edge configuration and screenshots from the Edge service.

**Comment by donskytech** [comment]
> @donskytech
> 
> Hello, it's not clear from the description, how this bug is related to the Edge service? Do you have issues on the Edge service, or only on the thingsboard.cloud? Please provide more details on your Edge configuration and screenshots from the Edge service.

Sorry, I probably made a mistake to where I should post my question.
This is in the Thingsboard Cloud Dashboard.
Can you transfer it for me to a proper project?

**Comment by donskytech** [comment]
> @donskytech
> 
> Hey, did you provide for the customers READ permissions for the Widget Type resource?

Hey,
I did not see this in the Thingsboard Cloud documentation Getting Started Guide
Where should I add this READ permission for the Widget Type Resource?
Thanks.

**Comment by donskytech** [comment]
Hey,
Kindly disregard this issue.  I recreated a new user with a new Gmail and it is working fine now.
