### ISSUE TITLE
[Question] How to uninstall thingsboard edge from ubuntu ?

### ISSUE THREAD

**Issue by sirapol** [thingsboard/thingsboard-edge#93]
**Component**

 * Installation
 
**Description**
A clear and concise details.

**Environment**

 * OS:  Linux rpi 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
 * ThingsBoard: tb-edge-3.5.1.1

Do you have uninstall.sh?

**Comment by volodymyr-babak** [comment]
@sirapol 

To remove Edge from Ubuntu please execute next command:
**`sudo dpkg --purge tb-edge`**
