### ISSUE TITLE
ThingsBoard Edge PE instance is showing API limitations

### ISSUE THREAD

**Issue by akseerali** [thingsboard/thingsboard-edge#98]
**Component**
 * Generic

**Description**
We have been using ThingsBoard Edge PE since April 2023 and had unlimited API support for the edge. Now, the edge shows limitations that are the same as cloud subscriptions. Due to this issue, the JavaScript execution limit is reached at the edge due to filtering the data before sending it to the cloud. The edge is also showing limited "Data points storage days".

* Question: Is it a bug, or has ThingsBoard added this as a feature in the new version? Is it possible to have unlimited API support like before?

Here is the screenshot of edge:
![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/aae5bb5f-4db3-4043-bdd9-b542955620ac)

**Environment**
 * OS:  Ubuntu 22.04
 * ThingsBoard: 3.6.2EDGEPE
 * Browser: Chrome Version 121.0.6167.160

**Comment by akseerali** [comment]
Update: TB Edge PE instance didn't have an API limitations issue. After upgrading the Edge PE version to 3.6.2, we are having issues reverting to the 3.6.1 version. The edge container keeps restarting.

Please release a fix for the 3.6.2 API limitations issue. 

Our team has also observed a synchronization issue between the Edge PE 3.6.1 and Cloud Platform 3.6.2. We will raise that issue for information.

**Comment by volodymyr-babak** [comment]
@akseerali 

Starting from version 3.6.2, ThingsBoard PE Edge fetches settings from the cloud instance and uses the configurations set on the cloud. 
We'll discuss possible fixes for this issue with the team and provide a solution in the next release, which is coming soon. Apologies for any inconvenience caused.

**Comment by AndriiLandiak** [comment]
Hello, @akseerali. 

Thank you for reaching out with your issue. We're pleased to inform you that we've already implemented a fix to allow unlimited API usage on Edge, the details are on: https://github.com/thingsboard/thingsboard-edge/commit/f776f9fcf93cae878ba511e0523361e2f0ff460c. 
TB's PR for handling rate limits for uplink messages: https://github.com/thingsboard/thingsboard/pull/10230

This update will be included in our next release, scheduled for the second week of March.
Thanks a lot!

**Comment by akseerali** [comment]
Hi @AndriiLandiak 

Please let us know the new TB Edge PE update release date. Thanks

**Comment by AndriiLandiak** [comment]
Hey @akseerali,

Great news! The newest versions, 3.6.3 of Thingsboard and Edge, are out now! Additionally, tomorrow, we're expecting the release of Thingsboard Edge PE.

**Comment by akseerali** [comment]
Hi @AndriiLandiak 

We have just updated the edge PE from 3.6.2 to 3.6.3, and there are still API limitations.
The current cloud version is 3.6.2.3PAAS. Does the cloud version need to be the same version to apply changes?

Here is the screenshot:
![tb-edge-screenshot](https://github.com/thingsboard/thingsboard-edge/assets/35078099/3d250b2c-4f2a-4c9a-815e-05f644b6db46)

**Comment by AndriiLandiak** [comment]
Hi, @akseerali. 

Thank you for your inquiry. I want to emphasize that there's no need to rush and update Edge before TB is updated. If you're utilizing a PAAS, it's advisable to wait for its upgrade before proceeding Edge upgrade, as we cannot guarantee that everything will work fine.
![image](https://github.com/thingsboard/thingsboard-edge/assets/50847617/d35ba09b-4b32-4544-ae43-54f1c37893a1)

Yes, you are correct. To implement these changes, we'll need to synchronize with version 3.6.3. As far as I'm aware, you should receive a message regarding the scheduled PAAS upgrade on Monday.

**Comment by akseerali** [comment]
Hi @AndriiLandiak 

The API issue is resolved after successfully upgrading the Edge version from 3.6.2 to 3.6.3.

We have one more query. After the upgrade, the TB Cloud shows many downlink messages containing old attributes and telemetry data, raising "Edge communication failure" notification alerts. Please see the attached screenshot of the downlink messages for your reference.

![image](https://github.com/thingsboard/thingsboard-edge/assets/35078099/f03ceea2-9826-4bd5-b7d5-8f1fb238b92d)

**Comment by AndriiLandiak** [comment]
Hi, @akseerali. 

Thank you for sharing your insights on the API limitation issue!

To gain a better understanding of the "Edge communication failure," I must admit, that we currently observe a 30-minute interval between the dispatch of the same error notifications, facilitated by the NotificationCenter. Screenshots of these notifications would be invaluable in determining whether it is a repetitive error message causing the overflow. If the frequency of these messages is excessive, consider deactivating this specific notification rule by following the provided instructions: https://thingsboard.cloud/notification/rules
![image](https://github.com/thingsboard/thingsboard-edge/assets/50847617/6a13eb89-45ce-4c50-8d33-10bfc77554fb)
